apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
  # find all files in infra folder
    manifests:
      - ./infra/k8s/*
# dont push to docker hub
build:
  local:
    push: false
    # maintain pod in specified directories in image
  artifacts:
    - image: cygnetops/client-95
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: cygnetops/comments-84
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: cygnetops/event-bus-85
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: cygnetops/moderation-84
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: cygnetops/posts-95
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: cygnetops/query-84
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
